
UPDATE tblBOMenu SET fldImageFile = 'RESOURCES.gif' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =10;
UPDATE tblBOMenu SET fldImageFile = 'Family.gif' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = 'Receivables.ico' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =3;
UPDATE tblBOMenu SET fldImageFile = 'StoreLarge.ico' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =5;
UPDATE tblBOMenu SET fldImageFile = 'workflow.gif' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =6;

UPDATE tblBOMenu SET fldImageFile = '13_12_b.png' WHERE fldComponent=1 AND fldFunctionID = 31 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_04_a.png' WHERE fldComponent=1 AND fldFunctionID = 97 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Customers.Ico' WHERE fldComponent=2 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Orders.ico' WHERE fldComponent=2 AND fldFunctionID = 5 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = 'CustGroups.ico' WHERE fldComponent=2 AND fldFunctionID = 3 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_13_a.png' WHERE fldComponent=6 AND fldFunctionID = 18 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_perm_contact_calendar_white_18dp.png' WHERE fldComponent=2 AND fldFunctionID = 9 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_15_a.png' WHERE fldComponent=6 AND fldFunctionID = 49 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_16_a.png' WHERE fldComponent=2 AND fldFunctionID = 24 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = '02_18_a.png' WHERE fldComponent=2 AND fldFunctionID = 15 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_contact_support_white_18dp.png' WHERE fldComponent=2 AND fldFunctionID = 19 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_20_a.png' WHERE fldComponent=6 AND fldFunctionID = 63 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_21_a.png' WHERE fldComponent=6 AND fldFunctionID = 64 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_13_b.png' WHERE fldComponent=6 AND fldFunctionID = 99 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_15_a.png' WHERE fldComponent=6 AND fldFunctionID = 49 AND fldParameter1 =6005;
UPDATE tblBOMenu SET fldImageFile = '02_24_b.png' WHERE fldComponent=2 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_25_c.png' WHERE fldComponent=2 AND fldFunctionID = 25 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '02_10_c.png' WHERE fldComponent=2 AND fldFunctionID = 32 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '01_03_b.png' WHERE fldComponent=4 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '03_11_a.png' WHERE fldComponent=4 AND fldFunctionID = 2 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '03_12_a.png' WHERE fldComponent=6 AND fldFunctionID = 16 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_card_giftcard_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 17 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_credit_card_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =381;
UPDATE tblBOMenu SET fldImageFile = '03_15_a.png' WHERE fldComponent=6 AND fldFunctionID = 46 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '03_16_b.png' WHERE fldComponent=6 AND fldFunctionID = 56 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_block_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =39;
UPDATE tblBOMenu SET fldImageFile = 'Currencies.png' WHERE fldComponent=4 AND fldFunctionID = 24 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_account_balance_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 24 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '03_20_c.png' WHERE fldComponent=4 AND fldFunctionID = 43 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '00_10_b.png' WHERE fldComponent=6 AND fldFunctionID = 86 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'NULL' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =31;
UPDATE tblBOMenu SET fldImageFile = 'Terminals.ico' WHERE fldComponent=3 AND fldFunctionID = 7 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_event_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =42;
UPDATE tblBOMenu SET fldImageFile = '04_12_b.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =43;
UPDATE tblBOMenu SET fldImageFile = '46_12_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =46;
UPDATE tblBOMenu SET fldImageFile = 'm029.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44;
UPDATE tblBOMenu SET fldImageFile = '04_15_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =45;
UPDATE tblBOMenu SET fldImageFile = '04_16_c.png' WHERE fldComponent=3 AND fldFunctionID = 8 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_date_range_white_18dp.png' WHERE fldComponent=10 AND fldFunctionID = 2 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Reports.gif' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =48;
UPDATE tblBOMenu SET fldImageFile = '04_19_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =68;
UPDATE tblBOMenu SET fldImageFile = '04_20_a.png' WHERE fldComponent=3 AND fldFunctionID = 8 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = '04_21_a.png' WHERE fldComponent=3 AND fldFunctionID = 21 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '04_22_a.png' WHERE fldComponent=3 AND fldFunctionID = 22 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '13_10_a.png' WHERE fldComponent=1 AND fldFunctionID = 25 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Reports.gif' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Reports.gif' WHERE fldComponent=5 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent=5 AND fldFunctionID = 3 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = '05_12_b.png' WHERE fldComponent=5 AND fldFunctionID = 5 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '05_13_b.png' WHERE fldComponent=12 AND fldFunctionID = 2 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '05_14_a.png' WHERE fldComponent=12 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '05_15_b.png' WHERE fldComponent=5 AND fldFunctionID = 9 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '05_16_c.png' WHERE fldComponent=5 AND fldFunctionID = 11 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '05_17_b.png' WHERE fldComponent=5 AND fldFunctionID = 10 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_table_chart_white_18dp.png' WHERE fldComponent=5 AND fldFunctionID = 15 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '00_10_b.png' WHERE fldComponent=1 AND fldFunctionID = 30 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '06_10_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '06_11_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 3 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_chat_bubble_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =70;
UPDATE tblBOMenu SET fldImageFile = 'baseline_swap_vertical_circle_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =63;
UPDATE tblBOMenu SET fldImageFile = 'baseline_build_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =65;
UPDATE tblBOMenu SET fldImageFile = 'baseline_cloud_upload_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =66;
UPDATE tblBOMenu SET fldImageFile = 'baseline_verified_user_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =67;
UPDATE tblBOMenu SET fldImageFile = 'baseline_language_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 6 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '10_10_f.png' WHERE fldComponent=1 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '10_11_d.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =12;
UPDATE tblBOMenu SET fldImageFile = '10_12_a.png' WHERE fldComponent=0 AND fldFunctionID = 2 AND fldParameter1 =13;
UPDATE tblBOMenu SET fldImageFile = 'Promotions.ico' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =16;
UPDATE tblBOMenu SET fldImageFile = '10_14_b.png' WHERE fldComponent=4 AND fldFunctionID = 15 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '10_15_b.png' WHERE fldComponent=4 AND fldFunctionID = 26 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm038.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =17;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =4;
UPDATE tblBOMenu SET fldImageFile = '10_18_a.png' WHERE fldComponent=1 AND fldFunctionID = 98 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '10_19_d.png' WHERE fldComponent=1 AND fldFunctionID = 116 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '10_20_d.png' WHERE fldComponent=1 AND fldFunctionID = 7 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '12_10_e.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =121;
UPDATE tblBOMenu SET fldImageFile = '12_11_e.png' WHERE fldComponent=1 AND fldFunctionID = 21 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '12_12_b.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =124;
UPDATE tblBOMenu SET fldImageFile = '12_13_b.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =18;
UPDATE tblBOMenu SET fldImageFile = '12_14_a.png' WHERE fldComponent=1 AND fldFunctionID = 123 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '12_15_b.png' WHERE fldComponent=1 AND fldFunctionID = 127 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '12_16_b.png' WHERE fldComponent=1 AND fldFunctionID = 128 AND fldParameter1 =6;
UPDATE tblBOMenu SET fldImageFile = '12_17_b.png' WHERE fldComponent=1 AND fldFunctionID = 129 AND fldParameter1 =6;
UPDATE tblBOMenu SET fldImageFile = 'PriceLists.ico' WHERE fldComponent=1 AND fldFunctionID = 26 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '13_14_d.png' WHERE fldComponent=1 AND fldFunctionID = 81 AND fldParameter1 =5000;
UPDATE tblBOMenu SET fldImageFile = '13_15_b.png' WHERE fldComponent=1 AND fldFunctionID = 117 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = '13_16_a.png' WHERE fldComponent=1 AND fldFunctionID = 1 AND fldParameter1 =5001;
UPDATE tblBOMenu SET fldImageFile = 'Promotions.ico' WHERE fldComponent=1 AND fldFunctionID = 27 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Tickets.ico' WHERE fldComponent=4 AND fldFunctionID = 16 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Tickets2.ico' WHERE fldComponent=1 AND fldFunctionID = 108 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '16_13_b.png' WHERE fldComponent=1 AND fldFunctionID = 125 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '13_15_b.png' WHERE fldComponent=1 AND fldFunctionID = 110 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '17_10_c.png' WHERE fldComponent=1 AND fldFunctionID = 22 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '17_11_d.png' WHERE fldComponent=1 AND fldFunctionID = 29 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '17_12_d.png' WHERE fldComponent=1 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '05_12_b.png' WHERE fldComponent=1 AND fldFunctionID = 5 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '17_14_d.png' WHERE fldComponent=1 AND fldFunctionID = 6 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '17_15_b.png' WHERE fldComponent=1 AND fldFunctionID = 28 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = '17_17_b.png' WHERE fldComponent=1 AND fldFunctionID = 111 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '17_18_c.png' WHERE fldComponent=1 AND fldFunctionID = 112 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_room_white_18dp.png' WHERE fldComponent=1 AND fldFunctionID = 126 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '12_13_b.png' WHERE fldComponent=1 AND fldFunctionID = 92 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =11;
UPDATE tblBOMenu SET fldImageFile = 'NULL' WHERE fldComponent=6 AND fldFunctionID = 86 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'NULL' WHERE fldComponent=6 AND fldFunctionID = 86 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = 'NULL' WHERE fldComponent=6 AND fldFunctionID = 56 AND fldParameter1 =375;
UPDATE tblBOMenu SET fldImageFile = '39_10_a.png' WHERE fldComponent=4 AND fldFunctionID = 12 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '39_11_b.png' WHERE fldComponent=4 AND fldFunctionID = 10 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '39_12_a.png' WHERE fldComponent=4 AND fldFunctionID = 11 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '42_10_a.png' WHERE fldComponent=6 AND fldFunctionID = 14 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '42_11_c.png' WHERE fldComponent=6 AND fldFunctionID = 11 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'EOD.ico' WHERE fldComponent=6 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Calendar.ico' WHERE fldComponent=6 AND fldFunctionID = 19 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Calendar2.ico' WHERE fldComponent=6 AND fldFunctionID = 52 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Calendar.ico' WHERE fldComponent=6 AND fldFunctionID = 62 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'EJViewer.ico' WHERE fldComponent=3 AND fldFunctionID = 2 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '43_14_a.png' WHERE fldComponent=4 AND fldFunctionID = 23 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_receipt_white_18dp.png' WHERE fldComponent=4 AND fldFunctionID = 25 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm019.png' WHERE fldComponent=3 AND fldFunctionID = 13 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44_01_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4410;
UPDATE tblBOMenu SET fldImageFile = '44_02_b.png' WHERE fldComponent=4 AND fldFunctionID = 20 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44_03_c.png' WHERE fldComponent=4 AND fldFunctionID = 3 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm029.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4440;
UPDATE tblBOMenu SET fldImageFile = '44_05_b.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4450;
UPDATE tblBOMenu SET fldImageFile = 'm020.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4460;
UPDATE tblBOMenu SET fldImageFile = '45_10_d.png' WHERE fldComponent=10 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '45_11_b.png' WHERE fldComponent=6 AND fldFunctionID = 31 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Report.gif' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =6;
UPDATE tblBOMenu SET fldImageFile = '45_13_b.png' WHERE fldComponent=10 AND fldFunctionID = 3 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm030.png' WHERE fldComponent=6 AND fldFunctionID = 31 AND fldParameter1 =5001;
UPDATE tblBOMenu SET fldImageFile = '46_11_b.png' WHERE fldComponent=3 AND fldFunctionID = 18 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '46_12_a.png' WHERE fldComponent=3 AND fldFunctionID = 16 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '46_13_b.png' WHERE fldComponent=3 AND fldFunctionID = 17 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '46_14_b.png' WHERE fldComponent=3 AND fldFunctionID = 23 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'ReportsSetup.ico' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =8;
UPDATE tblBOMenu SET fldImageFile = 'ReportsSetup.ico' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =3;
UPDATE tblBOMenu SET fldImageFile = 'ReportsSetup.ico' WHERE fldComponent=5 AND fldFunctionID = 4 AND fldParameter1 =7;
UPDATE tblBOMenu SET fldImageFile = 'Clock.ico' WHERE fldComponent=11 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 85 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_sync_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 45 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=8 AND fldFunctionID = 2 AND fldParameter1 =20;
UPDATE tblBOMenu SET fldImageFile = '42_15_a.png' WHERE fldComponent=6 AND fldFunctionID = 48 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = 'baseline_play_circle_filled_white_18dp.png' WHERE fldComponent=20 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm043.png' WHERE fldComponent=6 AND fldFunctionID = 65 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=1 AND fldFunctionID = 119 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm043.png' WHERE fldComponent=6 AND fldFunctionID = 66 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 69 AND fldParameter1 =3;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 69 AND fldParameter1 =5;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 69 AND fldParameter1 =6;
UPDATE tblBOMenu SET fldImageFile = '63_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 75 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = '12_14_a.png' WHERE fldComponent=1 AND fldFunctionID = 123 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm043.png' WHERE fldComponent=6 AND fldFunctionID = 55 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm043.png' WHERE fldComponent=6 AND fldFunctionID = 83 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_access_time_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_info_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 62 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '65_12_a.png' WHERE fldComponent=6 AND fldFunctionID = 32 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '65_13_a.png' WHERE fldComponent=0 AND fldFunctionID = 5 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '65_14_a.png' WHERE fldComponent=6 AND fldFunctionID = 54 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '65_15_a.png' WHERE fldComponent=6 AND fldFunctionID = 79 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '65_16_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4490;
UPDATE tblBOMenu SET fldImageFile = '65_17_a.png' WHERE fldComponent=0 AND fldFunctionID = 11 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_folder_white_18dp.png' WHERE fldComponent=0 AND fldFunctionID = 12 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm043.png' WHERE fldComponent=20 AND fldFunctionID = 2 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = 'baseline_play_circle_filled_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 10 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '66_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 3 AND fldParameter1 =0;
UPDATE tblBOMenu SET fldImageFile = '66_12_a.png' WHERE fldComponent=6 AND fldFunctionID = 42 AND fldParameter1 =0;
UPDATE tblBOMenu SET fldImageFile = '66_13_a.png' WHERE fldComponent=6 AND fldFunctionID = 3 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = '66_14_a.png' WHERE fldComponent=6 AND fldFunctionID = 42 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = 'baseline_verified_user_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 13 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_verified_user_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 12 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '67_12_b.png' WHERE fldComponent=6 AND fldFunctionID = 43 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '68_10_a.png' WHERE fldComponent=15 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '68_11_a.png' WHERE fldComponent=15 AND fldFunctionID = 3 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '68_12_a.png' WHERE fldComponent=15 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '68_13_a.png' WHERE fldComponent=15 AND fldFunctionID = 7 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm044.png' WHERE fldComponent=15 AND fldFunctionID = 7 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = 'baseline_all_inbox_white_18dp.png' WHERE fldComponent=15 AND fldFunctionID = 7 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = 'Configuration.ico' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =684;
UPDATE tblBOMenu SET fldImageFile = '68_17_b.png' WHERE fldComponent=15 AND fldFunctionID = 11 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '70_10_b.png' WHERE fldComponent=3 AND fldFunctionID = 5 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_email_white_18dp.png' WHERE fldComponent=0 AND fldFunctionID = 7 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_sms_white_18dp.png' WHERE fldComponent=0 AND fldFunctionID = 8 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '70_13_a.png' WHERE fldComponent=0 AND fldFunctionID = 9 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'Orders.ico' WHERE fldComponent=1 AND fldFunctionID = 91 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '121_11_a.png' WHERE fldComponent=1 AND fldFunctionID = 85 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '121_14_a.png' WHERE fldComponent=1 AND fldFunctionID = 124 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm033.png' WHERE fldComponent=1 AND fldFunctionID = 90 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = 'm034.png' WHERE fldComponent=1 AND fldFunctionID = 90 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = '381_10_a.png' WHERE fldComponent=6 AND fldFunctionID = 23 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '381_11_a.png' WHERE fldComponent=6 AND fldFunctionID = 78 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '381_12_b.png' WHERE fldComponent=6 AND fldFunctionID = 37 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '381_12_b.png' WHERE fldComponent=6 AND fldFunctionID = 57 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '381_14_a.png' WHERE fldComponent=4 AND fldFunctionID = 53 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '684_10_a.png' WHERE fldComponent=15 AND fldFunctionID = 6 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '684_11_a.png' WHERE fldComponent=15 AND fldFunctionID = 5 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '684_12_a.png' WHERE fldComponent=15 AND fldFunctionID = 8 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_touch_app_white_18dp.png' WHERE fldComponent=4 AND fldFunctionID = 21 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4410_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 14 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4410_03_b.png' WHERE fldComponent=4 AND fldFunctionID = 13 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4410_04_b.png' WHERE fldComponent=4 AND fldFunctionID = 27 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_email_white_18dp.png' WHERE fldComponent=4 AND fldFunctionID = 51 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_headset_mic_white_18dp.png' WHERE fldComponent=2 AND fldFunctionID = 17 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4411_02_a.png' WHERE fldComponent=2 AND fldFunctionID = 18 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4411_03_a.png' WHERE fldComponent=2 AND fldFunctionID = 20 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4411_04_a.png' WHERE fldComponent=2 AND fldFunctionID = 21 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4411_05_a.png' WHERE fldComponent=2 AND fldFunctionID = 22 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4440_01_a.png' WHERE fldComponent=13 AND fldFunctionID = 1 AND fldParameter1 =3;
UPDATE tblBOMenu SET fldImageFile = '4440_02_b.png' WHERE fldComponent=3 AND fldFunctionID = 1 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4440_03_c.png' WHERE fldComponent=13 AND fldFunctionID = 2 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4440_04_b.png' WHERE fldComponent=3 AND fldFunctionID = 19 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4440_05_b.png' WHERE fldComponent=3 AND fldFunctionID = 20 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4450_01_b.png' WHERE fldComponent=3 AND fldFunctionID = 12 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4450_02_a.png' WHERE fldComponent=3 AND fldFunctionID = 15 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4450_03_a.png' WHERE fldComponent=4 AND fldFunctionID = 22 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4450_04_a.png' WHERE fldComponent=4 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4455_02_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =4455;
UPDATE tblBOMenu SET fldImageFile = '4450_06_a.png' WHERE fldComponent=1 AND fldFunctionID = 114 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4450_07_a.png' WHERE fldComponent=4 AND fldFunctionID = 40 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4455_01_a.png' WHERE fldComponent=4 AND fldFunctionID = 8 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4455_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 9 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_01_a.png' WHERE fldComponent=4 AND fldFunctionID = 17 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 19 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_03_a.png' WHERE fldComponent=1 AND fldFunctionID = 93 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_04_a.png' WHERE fldComponent=1 AND fldFunctionID = 99 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm010.png' WHERE fldComponent=6 AND fldFunctionID = 72 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_square_foot_white_18dp.png' WHERE fldComponent=1 AND fldFunctionID = 2 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_07_b.png' WHERE fldComponent=1 AND fldFunctionID = 115 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_08_a.png' WHERE fldComponent=1 AND fldFunctionID = 121 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_09_b.png' WHERE fldComponent=6 AND fldFunctionID = 22 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '01_02_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44610;
UPDATE tblBOMenu SET fldImageFile = 'baseline_assignment_turned_in_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 58 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_12_a.png' WHERE fldComponent=4 AND fldFunctionID = 34 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '68_12_a.png' WHERE fldComponent=4 AND fldFunctionID = 35 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_room_service_white_18dp.png' WHERE fldComponent=4 AND fldFunctionID = 38 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_15_a.png' WHERE fldComponent=6 AND fldFunctionID = 30 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_16_a.png' WHERE fldComponent=6 AND fldFunctionID = 36 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_17_a.png' WHERE fldComponent=1 AND fldFunctionID = 109 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm037.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44618;
UPDATE tblBOMenu SET fldImageFile = 'm037.png' WHERE fldComponent=4 AND fldFunctionID = 48 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_20_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44620;
UPDATE tblBOMenu SET fldImageFile = '4460_21_a.png' WHERE fldComponent=10 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_local_gas_station_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44622;
UPDATE tblBOMenu SET fldImageFile = 'baseline_fastfood_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44623;
UPDATE tblBOMenu SET fldImageFile = 'baseline_local_shipping_white_18dp.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44624;
UPDATE tblBOMenu SET fldImageFile = '44650_03_a.png' WHERE fldComponent=6 AND fldFunctionID = 68 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_26_a.png' WHERE fldComponent=4 AND fldFunctionID = 47 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_27_a.png' WHERE fldComponent=4 AND fldFunctionID = 49 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_email_white_18dp.png' WHERE fldComponent=4 AND fldFunctionID = 51 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4460_29_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44629;
UPDATE tblBOMenu SET fldImageFile = '4461_50_a.png' WHERE fldComponent IS NULL AND fldFunctionID = 2 AND fldParameter1 =44650;
UPDATE tblBOMenu SET fldImageFile = '4480_11_a.png' WHERE fldComponent=4 AND fldFunctionID = 33 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '4480_12_a.png' WHERE fldComponent=4 AND fldFunctionID = 32 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_account_box_white_18dp.png' WHERE fldComponent=2 AND fldFunctionID = 13 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_perm_phone_msg_white_18dp.png' WHERE fldComponent=2 AND fldFunctionID = 12 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm047.png' WHERE fldComponent=2 AND fldFunctionID = 16 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'm047.png' WHERE fldComponent=2 AND fldFunctionID = 33 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'NULL' WHERE fldComponent=2 AND fldFunctionID = 34 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44618_01_a.png' WHERE fldComponent=4 AND fldFunctionID = 28 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44618_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 36 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44618_03_a.png' WHERE fldComponent=0 AND fldFunctionID = 12 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44620_01_a.png' WHERE fldComponent=4 AND fldFunctionID = 29 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44620_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 30 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44620_03_a.png' WHERE fldComponent=4 AND fldFunctionID = 31 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44620_04_a.png' WHERE fldComponent=6 AND fldFunctionID = 82 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44620_05_a.png' WHERE fldComponent=6 AND fldFunctionID = 81 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_local_gas_station_white_18dp.png' WHERE fldComponent=3 AND fldFunctionID = 4 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44622_02_a.png' WHERE fldComponent=3 AND fldFunctionID = 6 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44623_01_a.png' WHERE fldComponent=4 AND fldFunctionID = 44 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44623_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 45 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44624_01_a.png' WHERE fldComponent=4 AND fldFunctionID = 41 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44624_02_a.png' WHERE fldComponent=2 AND fldFunctionID = 11 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44624_03_a.png' WHERE fldComponent=6 AND fldFunctionID = 80 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44624_04_a.png' WHERE fldComponent=2 AND fldFunctionID = 26 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44629_01_b.png' WHERE fldComponent=4 AND fldFunctionID = 50 AND fldParameter1 =1;
UPDATE tblBOMenu SET fldImageFile = '44629_02_a.png' WHERE fldComponent=4 AND fldFunctionID = 50 AND fldParameter1 =3;
UPDATE tblBOMenu SET fldImageFile = '44629_03_a.png' WHERE fldComponent=4 AND fldFunctionID = 50 AND fldParameter1 =2;
UPDATE tblBOMenu SET fldImageFile = 'm010.png' WHERE fldComponent=6 AND fldFunctionID = 72 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_local_activity_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 71 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44650_03_a.png' WHERE fldComponent=6 AND fldFunctionID = 68 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44650_04_a.png' WHERE fldComponent=3 AND fldFunctionID = 14 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = '44650_05_a.png' WHERE fldComponent=1 AND fldFunctionID = 118 AND fldParameter1 IS NULL;
UPDATE tblBOMenu SET fldImageFile = 'baseline_assignment_turned_in_white_18dp.png' WHERE fldComponent=6 AND fldFunctionID = 58 AND fldParameter1 IS NULL;
